import { useEffect, useState } from "react";

type SeasonType = "reset" | "recovery" | "maintain" | "boost" | "special";

const SEASON_FLOWERS: Record<SeasonType, { emoji: string; name: string; latin: string; color: string }> = {
  reset:    { emoji: "🌵", name: "Cactus",   latin: "Cactaceae",   color: "#7EC8A0" },
    recovery: { emoji: "🌿", name: "Aloe",     latin: "Aloe Vera",   color: "#A8D5A2" },
      maintain: { emoji: "💜", name: "Lavender", latin: "Lavandula",   color: "#C9A8E0" },
        boost:    { emoji: "🌹", name: "Rose",     latin: "Rosa",        color: "#E8A0A0" },
          special:  { emoji: "🌸", name: "Orchid",   latin: "Orchidaceae", color: "#F0B8D8" },
          };

          export const FlowerSeasonBadge = ({ season }: { season: string | null }) => {
            const [visible, setVisible] = useState(false);
              const f = season ? SEASON_FLOWERS[season as SeasonType] : null;

                useEffect(() => {
                    setVisible(false);
                        const t = setTimeout(() => setVisible(true), 300);
                            return () => clearTimeout(t);
                              }, [season]);

                                if (!f) return null;

                                  return (
                                      <div style={{
                                            display: "flex",
                                                  flexDirection: "column",
                                                        alignItems: "flex-end",
                                                              gap: "2px",
                                                                    opacity: visible ? 1 : 0,
                                                                          transform: visible ? "translateY(0)" : "translateY(-8px)",
                                                                                transition: "opacity 0.7s ease, transform 0.7s ease",
                                                                                    }}>
                                                                                          <div style={{
                                                                                                  width: "40px",
                                                                                                          height: "40px",
                                                                                                                  borderRadius: "50%",
                                                                                                                          background: "rgba(255,255,255,0.08)",
                                                                                                                                  border: "1px solid rgba(255,255,255,0.15)",
                                                                                                                                          display: "flex",
                                                                                                                                                  alignItems: "center",
                                                                                                                                                          justifyContent: "center",
                                                                                                                                                                  fontSize: "20px",
                                                                                                                                                                          boxShadow: `0 0 12px ${f.color}55`,
                                                                                                                                                                                }}>
                                                                                                                                                                                        {f.emoji}
                                                                                                                                                                                              </div>
                                                                                                                                                                                                    <span style={{
                                                                                                                                                                                                            fontSize: "12px",
                                                                                                                                                                                                                    fontWeight: 300,
                                                                                                                                                                                                                            letterSpacing: "0.12em",
                                                                                                                                                                                                                            i m p o r t   {  cuosleoErf:f efc.tc,o luosre,S
                                                                                                                                                                                                                            t a t e   }   f rtoemx t"Arleiagcnt:" ;"
                                                                                                                                                                                                                            r
                                                                                                                                                                                                                            itgyhpte" ,S
                                                                                                                                                                                                                            e a s o n T y p el i=n e"Hreeisgehtt":  |1 ."2r,e
                                                                                                                                                                                                                            c o v e r y "} }|> 
                                                                                                                                                                                                                            " m a i n t a i n{"f .|n a"mbeo}o
                                                                                                                                                                                                                            s t "   |   "<s/psepcaina>l
                                                                                                                                                                                                                            " ; 
                                                                                                                                                                                                                             
                                                                                                                                                                                                                              c o n<sstp aSnE AsStOyNl_eF=L{O{W
                                                                                                                                                                                                                              E R S :   R e c ofrodn<tSSeiazseo:n T"y9ppex," ,{
                                                                                                                                                                                                                                e m o j i :   sftornitnSgt;y lnea:m e":i tsatlriicn"g,;
                                                                                                                                                                                                                                  l a t i n :   sltertitnegr;S pcaoclionrg::  s"t0r.i0n8ge m}">, 
                                                                                                                                                                                                                                  =   { 
                                                                                                                                                                                                                                       r e sceotl:o r :   "{r gebmao(j2i5:5 ,"2🌵"5,5 ,n2a5m5e,:0 ."3C5a)c"t,u
                                                                                                                                                                                                                                       s " ,       l a ttienx:t A"lCiagcnt:a c"eraieg"h,t " , 
                                                                                                                                                                                                                                       c o l o r :  }"}#>7
                                                                                                                                                                                                                                       E C 8 A 0 "   } ,{
                                                                                                                                                                                                                                       f . lraetcionv}e
                                                                                                                                                                                                                                       r y :   {   e<m/osjpia:n >"
                                                                                                                                                                                                                                       🌿 " ,   n<a/mdei:v >"
                                                                                                                                                                                                                                       A l o)e;"
                                                                                                                                                                                                                                       ,} ; 
                                                                                                                                                                                                                                          latin: "Aloe Vera",   color: "#A8D5A2" },
                                                                                                                                                                                                                                            maintain: { emoji: "💜", name: "Lavender", latin: "Lavandula",   color: "#C9A8E0" },
                                                                                                                                                                                                                                              boost:    { emoji: "🌹", name: "Rose",     latin: "Rosa",        color: "#E8A0A0" },
                                                                                                                                                                                                                                                special:  { emoji: "🌸", name: "Orchid",   latin: "Orchidaceae", color: "#F0B8D8" },
                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                export const FlowerSeasonBadge = ({ season }: { season: string | null }) => {
                                                                                                                                                                                                                                                  const [visible, setVisible] = useState(false);
                                                                                                                                                                                                                                                    const f = season ? SEASON_FLOWERS[season as SeasonType] : null;

                                                                                                                                                                                                                                                      useEffect(() => {
                                                                                                                                                                                                                                                          setVisible(false);
                                                                                                                                                                                                                                                              const t = setTimeout(() => setVisible(true), 300);
                                                                                                                                                                                                                                                                  return () => clearTimeout(t);
                                                                                                                                                                                                                                                                    }, [season]);

                                                                                                                                                                                                                                                                      if (!f) return null;

                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                            <div style={{
                                                                                                                                                                                                                                                                                  display: "flex",
                                                                                                                                                                                                                                                                                        flexDirection: "column",
                                                                                                                                                                                                                                                                                              alignItems: "flex-end",
                                                                                                                                                                                                                                                                                                    gap: "2px",
                                                                                                                                                                                                                                                                                                          opacity: visible ? 1 : 0,
                                                                                                                                                                                                                                                                                                                transform: visible ? "translateY(0)" : "translateY(-8px)",
                                                                                                                                                                                                                                                                                                                      transition: "opacity 0.7s ease, transform 0.7s ease",
                                                                                                                                                                                                                                                                                                                          }}>
                                                                                                                                                                                                                                                                                                                                <div style={{
                                                                                                                                                                                                                                                                                                                                        width: "40px",
                                                                                                                                                                                                                                                                                                                                                height: "40px",
                                                                                                                                                                                                                                                                                                                                                        borderRadius: "50%",
                                                                                                                                                                                                                                                                                                                                                                background: "rgba(255,255,255,0.08)",
                                                                                                                                                                                                                                                                                                                                                                        border: "1px solid rgba(255,255,255,0.15)",
                                                                                                                                                                                                                                                                                                                                                                                display: "flex",
                                                                                                                                                                                                                                                                                                                                                                                        alignItems: "center",
                                                                                                                                                                                                                                                                                                                                                                                                justifyContent: "center",
                                                                                                                                                                                                                                                                                                                                                                                                        fontSize: "20px",
                                                                                                                                                                                                                                                                                                                                                                                                                boxShadow: `0 0 12px ${f.color}55`,
                                                                                                                                                                                                                                                                                                                                                                                                                      }}>
                                                                                                                                                                                                                                                                                                                                                                                                                              {f.emoji}
                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                          <span style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                  fontSize: "12px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                          fontWeight: 300,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  letterSpacing: "0.12em",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          color: f.color,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  textAlign: "right",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          lineHeight: 1.2,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {f.name}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fontSize: "9px",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    font