
-- Seed all hardcoded treatment items into package_options
-- New items for existing category: 리프팅·보톡스
INSERT INTO package_options (category, category_en, category_zh, name, name_en, name_zh, is_default, sort_order) VALUES
('리프팅·보톡스','Lifting·Botox','提升·肉毒素','슈링크 유니버스','Shrink Universe','超声刀',true,60),
('리프팅·보톡스','Lifting·Botox','提升·肉毒素','울쎄라 피프라임','Ulthera FiPrime','超声刀FiPrime',true,70),
('리프팅·보톡스','Lifting·Botox','提升·肉毒素','세르프 리프팅','Serf Lifting','高频提升',true,80),
('리프팅·보톡스','Lifting·Botox','提升·肉毒素','덴서티','Density','Density提升',true,90),
('리프팅·보톡스','Lifting·Botox','提升·肉毒素','온다 리프팅','Onda Lifting','极超短波提升',true,100),
('리프팅·보톡스','Lifting·Botox','提升·肉毒素','인모드','InMode','InMode提升',true,110),
('리프팅·보톡스','Lifting·Botox','提升·肉毒素','올리지오','Oligio','Oligio提升',true,120),
('리프팅·보톡스','Lifting·Botox','提升·肉毒素','티타늄 리프팅','Titanium Lifting','钛金提升',true,130),
('리프팅·보톡스','Lifting·Botox','提升·肉毒素','텐써마','Tensema','高频热能提升',true,140),
('리프팅·보톡스','Lifting·Botox','提升·肉毒素','텐쎄라','Tensera','超声波+高频复合提升',true,150),
('리프팅·보톡스','Lifting·Botox','提升·肉毒素','엠페이스','EmFace','RF+HIFES面部护理',true,160),
('리프팅·보톡스','Lifting·Botox','提升·肉毒素','볼뉴머','Volnumar','胶原蛋白再生提升',true,170),
('리프팅·보톡스','Lifting·Botox','提升·肉毒素','LDM 리프팅','LDM Lifting','LDM超声波提升',true,180),
('리프팅·보톡스','Lifting·Botox','提升·肉毒素','윤곽주사','Contour Injection','轮廓针',true,190),
-- 신규 카테고리: 필러·실리프팅
('필러·실리프팅','Filler·Thread','填充·线雕','턱끝 필러','Chin Filler','下巴填充',true,30),
('필러·실리프팅','Filler·Thread','填充·线雕','입술 필러','Lip Filler','唇部填充',true,40),
('필러·실리프팅','Filler·Thread','填充·线雕','코 필러','Nose Filler','鼻部填充',true,50),
('필러·실리프팅','Filler·Thread','填充·线雕','눈밑 필러','Under-eye Filler','眼下填充',true,60),
('필러·실리프팅','Filler·Thread','填充·线雕','애교살 필러','Aegyo-sal Filler','卧蚕填充',true,70),
('필러·실리프팅','Filler·Thread','填充·线雕','입꼬리 필러','Lip Corner Filler','嘴角填充',true,80),
('필러·실리프팅','Filler·Thread','填充·线雕','목주름 필러','Neck Wrinkle Filler','颈纹填充',true,90),
('필러·실리프팅','Filler·Thread','填充·线雕','스컬트라','Sculptra','童颜针',true,100),
('필러·실리프팅','Filler·Thread','填充·线雕','실리프팅','Thread Lifting','线雕提升',true,110),
-- 신규 카테고리: 스킨부스터
('스킨부스터','Skin Booster','皮肤助推器','스킨바이브','SkinVive','透明质酸助推',true,10),
('스킨부스터','Skin Booster','皮肤助推器','리쥬란 힐러','Rejuran Healer','婴儿针',true,20),
('스킨부스터','Skin Booster','皮肤助推器','리쥬란HB','Rejuran HB','婴儿针HB',true,30),
('스킨부스터','Skin Booster','皮肤助推器','아이리쥬란','Eye Rejuran','眼部婴儿针',true,40),
('스킨부스터','Skin Booster','皮肤助推器','쥬베룩 스킨','Juvelook Skin','胶原蛋白助推',true,50),
('스킨부스터','Skin Booster','皮肤助推器','쥬베룩 볼륨','Juvelook Volume','胶原蛋白丰盈',true,60),
('스킨부스터','Skin Booster','皮肤助推器','쥬베룩 아이','Juvelook Eye','眼部胶原蛋白',true,70),
('스킨부스터','Skin Booster','皮肤助推器','레디어스','Radiesse','微晶瓷',true,80),
('스킨부스터','Skin Booster','皮肤助推器','리바이브','Revive','甘油+HA复合',true,90),
('스킨부스터','Skin Booster','皮肤助推器','레티젠','Retizen','视黄醇+HA助推',true,100),
('스킨부스터','Skin Booster','皮肤助推器','리투오','Litoure','蛋白质+HA再生',true,110),
('스킨부스터','Skin Booster','皮肤助推器','엑소좀','Exosome','干细胞外泌体',true,120),
('스킨부스터','Skin Booster','皮肤助推器','미희주사','Mihee Injection','胶原蛋白注射',true,130),
('스킨부스터','Skin Booster','皮肤助推器','포텐자','Potenza','定制高频',true,140),
('스킨부스터','Skin Booster','皮肤助推器','콜라스터','Colaster','6种安瓿胶原蛋白',true,150),
('스킨부스터','Skin Booster','皮肤助推器','원데이 스킨부스터','One-day Skin Booster','一日皮肤助推',true,160),
-- 피부 관리 추가 항목
('피부 관리','Skin Care','皮肤护理','비타민관리','Vitamin Care','维生素护理',true,90),
('피부 관리','Skin Care','皮肤护理','크라이오관리','Cryo Care','冷冻护理',true,100),
('피부 관리','Skin Care','皮肤护理','이온자임','Ionzyme','离子导入',true,110),
('피부 관리','Skin Care','皮肤护理','라라필','Larafil','Larafil护理',true,120),
('피부 관리','Skin Care','皮肤护理','플라센타관리','Placenta Care','胎盘护理',true,130),
('피부 관리','Skin Care','皮肤护理','블랙헤드관리','Blackhead Care','黑头护理',true,140),
('피부 관리','Skin Care','皮肤护理','블랙필','Black Peel','黑色果酸',true,150),
('피부 관리','Skin Care','皮肤护理','예스필','Yes Peel','Yes果酸',true,160),
('피부 관리','Skin Care','皮肤护理','핑크필','Pink Peel','粉色果酸',true,170),
('피부 관리','Skin Care','皮肤护理','물방울관리','Water Drop Care','水滴护理',true,180),
('피부 관리','Skin Care','皮肤护理','필링 (단독)','Peeling','果酸换肤',true,190),
-- 신규 카테고리: 미백·색소
('미백·색소','Whitening·Pigment','美白·色素','엑셀V','ExcelV','ExcelV激光',true,10),
('미백·색소','Whitening·Pigment','美白·色素','피코토닝','Pico Toning','皮秒调色',true,20),
('미백·색소','Whitening·Pigment','美白·色素','피코프락셀','Pico Fraxel','皮秒点阵',true,30),
('미백·색소','Whitening·Pigment','美白·色素','미백토닝','Whitening Toning','美白调色',true,40),
('미백·색소','Whitening·Pigment','美白·色素','리팟레이저','Lipat Laser','祛斑激光',true,50),
('미백·색소','Whitening·Pigment','美白·色素','알라딘필링','Aladdin Peel','阿拉丁果酸',true,60),
('미백·색소','Whitening·Pigment','美白·色素','PHA필링','PHA Peel','PHA果酸',true,70),
('미백·색소','Whitening·Pigment','美白·色素','쿰스필링','Cooms Peel','Cooms果酸',true,80),
-- 여드름·흉터 추가 항목
('여드름·흉터','Acne·Scar','痘痘·疤痕','점/쥐젖/사마귀 제거','Mole/Skin Tag Removal','祛痣/赘生物',true,40),
('여드름·흉터','Acne·Scar','痘痘·疤痕','여드름 치료','Acne Treatment','痘痘治疗',true,50),
('여드름·흉터','Acne·Scar','痘痘·疤痕','아크네필링','Acne Peel','痘痘果酸',true,60),
('여드름·흉터','Acne·Scar','痘痘·疤痕','포텐자 얼굴전체','Potenza Full Face','全脸高频',true,70),
('여드름·흉터','Acne·Scar','痘痘·疤痕','카프리레이저','Capri Laser','控油激光',true,80),
-- 신규 카테고리: 지방분해
('지방분해','Fat Dissolving','溶脂','지방분해주사','Fat Dissolving Injection','溶脂针',true,10),
('지방분해','Fat Dissolving','溶脂','얼굴 지방분해주사','Face Fat Dissolving','面部溶脂',true,20),
('지방분해','Fat Dissolving','溶脂','바디 지방분해주사','Body Fat Dissolving','身体溶脂',true,30),
('지방분해','Fat Dissolving','溶脂','조각주사','Sculpt Injection','雕塑针',true,40),
('지방분해','Fat Dissolving','溶脂','브이올렛','Violet','提升+溶脂复合',true,50),
('지방분해','Fat Dissolving','溶脂','제로핏','ZeroFit','脂肪细胞凋亡',true,60),
('지방분해','Fat Dissolving','溶脂','벨라콜린','Belacolin','卡尼汀复合溶脂',true,70),
-- 신규 카테고리: 제모
('제모','Hair Removal','脱毛','젠틀맥스 남성제모','GentleMax Male','GentleMax男士',true,10),
('제모','Hair Removal','脱毛','젠틀맥스 여성제모','GentleMax Female','GentleMax女士',true,20),
('제모','Hair Removal','脱毛','아포지 남성제모','Apogee Male','Apogee男士',true,30),
('제모','Hair Removal','脱毛','아포지 여성제모','Apogee Female','Apogee女士',true,40),
('제모','Hair Removal','脱毛','다이오드 남성제모','Diode Male','二极管男士',true,50),
('제모','Hair Removal','脱毛','다이오드 여성제모','Diode Female','二极管女士',true,60),
('제모','Hair Removal','脱毛','SHR 제모','SHR Hair Removal','SHR脱毛',true,70),
-- 신규 카테고리: 수액·영양주사
('수액·영양주사','IV·Nutrition','输液·营养针','수액주사','IV Drip','输液',true,10),
('수액·영양주사','IV·Nutrition','输液·营养针','백옥주사','Jade Injection','白玉针',true,20),
('수액·영양주사','IV·Nutrition','输液·营养针','신데렐라주사','Cinderella Injection','灰姑娘针',true,30),
('수액·영양주사','IV·Nutrition','输液·营养针','비타민주사','Vitamin Injection','维生素针',true,40),
('수액·영양주사','IV·Nutrition','输液·营养针','태반주사','Placenta Injection','胎盘针',true,50),
('수액·영양주사','IV·Nutrition','输液·营养针','줄기세포','Stem Cell','干细胞',true,60);
