// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gaharylmkilooukxnipk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdhaGFyeWxta2lsb291a3huaXBrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4OTMxOTYsImV4cCI6MjA4ODQ2OTE5Nn0.vR6YoXrxxlQ0opmmV_x5LUSMEdCIchHGXjr4NZOt8NU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});